### ISSUE TITLE
InfracostSetup fails with error releases.filter is not a function in YAML pipeline

### ISSUE THREAD

**Issue by corporate-gadfly** [infracost/infracost-azure-devops#73]
For a project in Azure Repos, in an Azure DevOps YAML pipeline:
```
  # Install the Infracost CLI, see https://github.com/infracost/infracost-azure-devops#infracostsetup
  - task: InfracostSetup@1
    displayName: Setup Infracost
    inputs:
      apiKey: $(infracostApiKey)
```
I'm _(sometimes)_ seeing the following error:
```
Starting: Setup Infracost
==============================================================================
Task         : Infracost Setup Task
Description  : Sets up Infracost CLI in Azure Pipelines. Show cloud cost estimates for Terraform in pull requests.
Version      : 1.0.6
Author       : Infracost
Help         : 
==============================================================================
##[error]releases.filter is not a function
Finishing: Setup Infracost
```
Presumably this is due to some sort of API rate limiting for `https://api.github.com/repos/${user}/${name}/releases`.

Workaround is to set the `version` in the `inputs` parameter of the setup task, e.g.,:
```
  # Install the Infracost CLI, see https://github.com/infracost/infracost-azure-devops#infracostsetup
  - task: InfracostSetup@1
    displayName: Setup Infracost
    inputs:
      version: 0.10.17
      apiKey: $(infracostApiKey)
```
